### ISSUE TITLE
There is no build script

### ISSUE THREAD

**Issue by kazagkazag** [erasmo-marin/open-hax#1]
There is no build script in package.json, only watch script. When I used watch, I've got following errors:
`ERROR in ./client/Actions/GameActions.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../dispatcher/AppDispatcher in /home/kazag/work/openHax/client/Actions
 @ ./client/Actions/GameActions.jsx 7:21-59

ERROR in ./client/Actions/GameActions.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../constants/ActionTypes in /home/kazag/work/openHax/client/Actions
 @ ./client/Actions/GameActions.jsx 11:19-54

ERROR in ./client/Components/Room/index.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../../constants/ActionTypes in /home/kazag/work/openHax/client/Components/Room
 @ ./client/Components/Room/index.jsx 9:19-57

ERROR in ./client/Stores/ChatStore.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../constants/ActionTypes in /home/kazag/work/openHax/client/Stores
 @ ./client/Stores/ChatStore.jsx 9:19-54

ERROR in ./client/Stores/ChatStore.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../dispatcher/AppDispatcher in /home/kazag/work/openHax/client/Stores
 @ ./client/Stores/ChatStore.jsx 13:21-59

ERROR in ./client/Actions/ChatActions.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../dispatcher/AppDispatcher in /home/kazag/work/openHax/client/Actions
 @ ./client/Actions/ChatActions.jsx 7:21-59

ERROR in ./client/Actions/ChatActions.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../constants/ActionTypes in /home/kazag/work/openHax/client/Actions
 @ ./client/Actions/ChatActions.jsx 11:19-54

ERROR in ./client/Stores/GameStore.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../constants/ActionTypes in /home/kazag/work/openHax/client/Stores
 @ ./client/Stores/GameStore.jsx 9:19-54

ERROR in ./client/Stores/GameStore.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../dispatcher/AppDispatcher in /home/kazag/work/openHax/client/Stores
 @ ./client/Stores/GameStore.jsx 13:21-59
`

My node version:

`$ node -v
v6.9.2
$npm -v
3.10.9`

**Comment by erasmo-marin** [comment]
Hi, which operative system are you using? I think the problem is that there are some problems with case that I didn't detected because I work on mac, and mac OS is case insensitive, so capitalizing the folders import name should work for the while if you want to build it now:

change
dispatcher to Dispatcher
constants to Constants

Also, yeah, the build script is missing. I will push a fix and also I will upgrade to webpack 2 soon, thanks for your help.

**Comment by kazagkazag** [comment]
Ok, I will try and let you know. I use Ubuntu.

**Comment by kazagkazag** [comment]
I created PR, now "watch" script works on Ubuntu.

**Comment by erasmo-marin** [comment]
great, I will try to review it as soon as possible, also, changed the assignment to you

**Comment by ucemucar** [comment]
I got "missing script: build" error on Windows 10. 

C:\Users\\_USERNAME_\Desktop\Arc\hax>npm run build
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\\_USERNAME_\Desktop\Arc\hax\npm-debug.log

**Comment by erasmo-marin** [comment]
@VisionsX There is no build script yet, it's an error in Readme, but a watch script is available for development. You can still build without watch mode by just removing the --watch parameter in the watch script:
```
$ webpack --progress --colors
```
